# Goal: i  have to lint , build, test and push the image to docker hub
# for frontend and backend

name:  CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v7
      
      - name: set up node
        uses: actions/setup-node@v6 
        with:
          node-version: '20.x'

      - name: install dependencies
        run: npm install

      - name: lint code
        run: npm run lint   

      - name: test code
        run: npm run test

      - name: build code
        run: npm run build

  backend: 
