# Goal: i  have to lint , build, test and push the image to docker hub
# for frontend and backend

name:  CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: checkout code
        uses: actions/checkout@v7
      
      - name: set up node
        uses: actions/setup-node@v6 
        with:
          node-version: '24.x'

      - name: install dependencies
        run: npm install

      - name: lint code
        run: npm run lint   

      - name: test code
        run: npm run test

      - name: Docker login
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/devboard-frontend:latest

 # backend: 
