# Goal - i have to do sast for my code
name: code quality
on:
  workflow_call: # we can call this workflow from anywhere

jobs:
  SAST:
  runs-on: ubuntu-latest
  steps:
    - name: checkout code
      uses: actions/checkout@v7
    
    - name: set up node
      uses: actions/setup-node@v6 
      with:
        node-version: '24.x'

    - name: install dependencies
      run: npm install
      working-directory: frontend

    - name: lint code
      run: npm run lint   
      working-directory: frontend

    - name: setup Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.23'
        go-version-file: 'go.mod'
        cache-dependency-path: 'go.sum'
    
    - name: go lang formater
      run: go fmt
      working-directory: backend

    - name: go vet
      run: go vet
      working-directory: backend