#Goal - to ensure dependency and packages have been audited
name: Dependency Scan

on:
  workflow_call:

jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v7
        with:
          # Explicitly clear the token after downloading the code
          persist-credentials: false 
      
      - name: setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.22'
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'

      - name: Run Govulncheck
        uses: golang/govulncheck-action@v1
        with:
          working-directory: backend
          go-version-input: '1.22'
        

      - name: set up node
        uses: actions/setup-node@v6 
        with:
          node-version: '24.x'

      - name: Node Dependency Scan
        run: npm audit
        working-directory: frontend
