#Goal - to ensure dependency and packages have been audited
name: Dependency Scan

on:
  workflow_call:

jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v7
        with:
          # Explicitly clear the token after downloading the code
          persist-credentials: false 
      
      - name: setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.22'
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'

      - name: Install Compatible Govulncheck
        # Forces installation of v1.1.3, which works perfectly on Go 1.22
        run: go install golang.org/x/vuln/cmd/govulncheck@v1.1.3 

      - name: Run Govulncheck Scan
        continue-on-error: true
        # Changes directory to backend and executes the tool locally
        working-directory: backend
        run: govulncheck ./... > report/dependency-scan.txt
        
      

      - name: set up node
        uses: actions/setup-node@v6 
        with:
          node-version: '24.x'

      - name: Node Dependency Scan
        run: npm audit
        working-directory: frontend

      - name: Upload report Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dependency scan report          # Name of the downloaded zip file
          path: report/dependency-scan.txt       # Path to file or folder you want to upload
          retention-days: 5    
